---
dist: trusty
language: python
python: "2.7.12"

# Don't use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
      - python-pip

before_install:
  # Add the PPA that contains PHP 7 for Ubuntu Trusty
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Install via Ansible Galaxy to get all dependencies in meta/main.yml
  - ansible-galaxy install -f kso512.install-picocms

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the playbook and hope for no errors
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo

  # See what services we have
  - service --status-all

  # Run the playbook one more time and hope for no changes to make sure its idempotent
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
